<?php
$auponomarev_activityfixed_default_option = [
    'TIME_FIELD' => 'UF_CRM_LASTLEADTOUCH',
    'FIRSTLEADTOUCH_FIELD' => 'UF_CRM_FIRSTLEADTOUCH',
    'FIRSTDEALTOUCH_FIELD' => 'UF_CRM_FIRSTDEALTOUCH',
    'LASTDEALTOUCH_FIELD' => 'UF_CRM_LASTDEALTOUCH',
];